// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Jason Roughley <pis.controller@gmail.com>

#pragma once

#include <cstddef>
#include <cstdint>

inline namespace jf {

// The logo shown on the About box, as raw RGBA rather than as a PNG.
//
// Nothing decodes it. PNG carries its pixels DEFLATE-compressed, so reading one
// means an inflate implementation -- a parser, over a file, in a language where a
// parser bug is a memory-safety bug. For a picture the application ships and
// never changes, the pixels are known when the source is written, so they are
// written as pixels and no parser exists to be wrong.
//
// Generated by packaging/embed-logo.sh; see there to change it.
struct JScopeAboutLogo {
    static const unsigned char kRgba[];
    static const uint32_t      kWidth;
    static const uint32_t      kHeight;

    static size_t byteCount() { return size_t(kWidth) * kHeight * 4u; }
};

} // inline namespace jf
