#!/usr/bin/env bash
# Turn the About logo into a C++ source file of raw RGBA.
#
# THE BUILD DOES NOT DECODE ANYTHING. PNG is DEFLATE-compressed, so decoding one
# means an inflate implementation -- and that is a parser, running on a file, in a
# language where a parser bug is a memory-safety bug. For an image the application
# ships and never changes, none of that has to exist: the pixels are known when
# the source is written, so they are written as pixels.
#
# Run this when src/app/assets/jaytek-logo.png changes. It needs
# ImageMagick; the generated file is committed so an ordinary build does not.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
src="$root/src/app/assets/jaytek-logo.png"
out="$root/src/app/JScopeAboutLogo.cpp"
width=240

command -v convert >/dev/null || { echo "embed-logo: needs ImageMagick" >&2; exit 1; }
[ -f "$src" ] || { echo "embed-logo: no logo at $src" >&2; exit 1; }

# Separate calls rather than one read: `info:` prints no trailing newline, so
# `read` returns non-zero and set -e would end the script having done nothing.
w="$(convert "$src" -resize "${width}x" -format "%w" info:)"
h="$(convert "$src" -resize "${width}x" -format "%h" info:)"
tmp="$(mktemp)"; trap 'rm -f "$tmp"' EXIT
convert "$src" -resize "${width}x" -depth 8 RGBA:"$tmp"

{
  echo "// SPDX-License-Identifier: GPL-3.0-or-later"
  echo "// Copyright (C) 2026 Jason Roughley <pis.controller@gmail.com>"
  echo
  echo "// GENERATED by packaging/embed-logo.sh from assets/jaytek-logo.png."
  echo "// Do not edit: change the PNG and run the script."
  echo
  echo '#include "JScopeAboutLogo.h"'
  echo
  echo "inline namespace jf {"
  echo
  echo "const uint32_t JScopeAboutLogo::kWidth  = ${w}u;"
  echo "const uint32_t JScopeAboutLogo::kHeight = ${h}u;"
  echo
  echo "const unsigned char JScopeAboutLogo::kRgba[] = {"
  od -An -v -tu1 -w16 "$tmp" | sed 's/^ */    /; s/  */,/g; s/^,//; s/$/,/'
  echo "};"
  echo
  echo "} // inline namespace jf"
} > "$out"

echo "embed-logo: ${w}x${h}, $(stat -c%s "$tmp") bytes of RGBA -> $out"
